# Generated by Django 4.2.10 on 2024-03-17 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_reports'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='auth_code',
            new_name='access_token',
        ),
    ]
