# Generated by Django 4.2.10 on 2024-03-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0003_rename_auth_code_user_access_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='access_token',
            new_name='refresh_token',
        ),
    ]
