# Generated by Django 4.2.10 on 2024-03-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0004_rename_access_token_user_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
