# Generated by Django 4.2.10 on 2024-03-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0005_alter_reports_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='url',
            field=models.TextField(default='https://example.com'),
            preserve_default=False,
        ),
    ]
