# Generated by Django 4.2.10 on 2024-03-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0008_reports_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='image',
            field=models.ImageField(default='default.png', upload_to='reports/'),
        ),
    ]
