# Generated by Django 4.2.10 on 2024-10-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0009_alter_reports_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter_Recipients',
            fields=[
                ('email', models.TextField(primary_key=True, serialize=False)),
                ('subscribed', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reports',
            name='image',
            field=models.ImageField(default='\\default.png', upload_to='reports/'),
        ),
    ]
