# Generated by Django 4.2.10 on 2024-10-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0010_newsletter_recipients_alter_reports_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Professional', 'Professional'), ('Enterprise', 'Enterprise')], default='Basic', max_length=15),
        ),
    ]
